--  This package was generated by the Ada_Drivers_Library project wizard script
package ADL_Config is
   Board                          : constant String  := "STM32F407_Discovery"; -- From user input
   Architecture                   : constant String  := "ARM";               -- From board definition
   Vendor                         : constant String  := "STMicro";           -- From board definition
   Device_Family                  : constant String  := "STM32F4";           -- From board definition
   Device_Name                    : constant String  := "STM32F407VGTx";     -- From board definition
   CPU_Core                       : constant String  := "ARM Cortex-M4F";    -- From mcu definition
   High_Speed_External_Clock      : constant         := 8000000;             -- From board definition
   Number_Of_Interrupts           : constant         := 0;                   -- From user input
   Has_ZFP_Runtime                : constant String  := "False";             -- From board definition
   Has_Ravenscar_SFP_Runtime      : constant String  := "True";              -- From board definition
   Has_Ravenscar_Full_Runtime     : constant String  := "True";              -- From board definition
   Runtime_Profile                : constant String  := "ravenscar-full";    -- From user input
   Runtime_Name_Suffix            : constant String  := "stm32f4";           -- From board definition
   Runtime_Name                   : constant String  := "ravenscar-full-stm32f4"; -- From user input
   Use_Startup_Gen                : constant Boolean := True;                -- From user input
   Has_Custom_Memory_Area_1       : constant Boolean := True;                -- From user input
   Custom_Mem_1_Kind              : constant String  := "RAM";               -- From user input
   Custom_Mem_1_Addr              : constant         := 0;                   -- From user input
   Custom_Mem_1_Size              : constant         := 1;                   -- From user input
   Custom_Mem_1_Name              : constant String  := "1";                 -- From user input
   Has_Custom_Memory_Area_2       : constant Boolean := True;                -- From user input
   Custom_Mem_2_Kind              : constant String  := "RAM";               -- From user input
   Custom_Mem_2_Addr              : constant         := 1;                   -- From user input
   Custom_Mem_2_Size              : constant         := 1;                   -- From user input
   Custom_Mem_2_Name              : constant String  := "1";                 -- From user input
   Has_Custom_Memory_Area_3       : constant Boolean := False;               -- From user input
   Boot_Memory                    : constant String  := "n";                 -- From user input
   Max_Path_Length                : constant         := 1024;                -- From user input
   Max_Mount_Points               : constant         := 2;                   -- From user input
   Max_Mount_Name_Length          : constant         := 128;                 -- From user input
end ADL_Config;
